import axios from "axios";

const names = [
    "Praneeth Shalinda Adikari A. A.",
    "Michael David ADAMS",
    "Divesh AGGARWAL",
    "AI Xin",
    "Boyd ANDERSON",
    "Arnab BHATTACHARYYA",
    "Anand BHOJAN",
    "Bruno BODIN",
    "Stephane BRESSAN",
    "Xavier Roger Gilbert BRESSON",
    "Cristina CARBUNARU",
    "Trevor Erik CARLSON",
    "Diptarka CHAKRABORTY",
    "CHAN Chee Yong",
    "CHAN Mun Choon",
    "CHANG Ee Chien",
    "CHANG Yi-Jun",
    "CHEN Nan",
    "CHEN Tsuhan",
    "Alan CHENG Holun",
    "Henry CHIA Wai Kit",
    "CHIN Wei Ngan",
    "CHONG Ket Fah",
    "CHUA Tat Seng",
    "CUI Wei",
    "Ashish Deepak DANDEKAR",
    "Olivier Gerard Henri Marie DANVY",
    "DONG Jin Song",
    "EE Kiam Keong",
    "Nicholas Mac Gregor GARCIA",
    "Seth Lewis GILBERT",
    "GOH Khim Yong",
    "HAHN Jungpil",
    "Steven HALIM",
    "HE Bingsheng",
    "HENG Cheng Suang",
    "Martin HENZ",
    "Bryan HOOI Kuen Yew",
    "David HSU",
    "Wynne HSU",
    "HU Conghui",
    "HUANG Ke-Wei",
    "HUANG Zhiyong",
    "Joxan JAFFAR",
    "Rahul JAIN",
    "Sanjay JAIN",
    "Djordje JEVDJIC",
    "JIANG Kan",
    "JIN Chen",
    "KAN Min Yen",
    "Atreyi KANKANHALLI",
    "Mohan KANKANHALLI",
    "Varun KARAMSHETTY",
    "Aditya KARANAM",
    "Kenji KAWAGUCHI",
    "KHOO Siau Cheng",
    "Stanley KOK",
    "Nakyung KYUNG",
    "Nitya LAKSHMANAN",
    "LEE Boon Kee",
    "LEE Gim Hee",
    "LEE Mong Li",
    "LEE Wee Sun",
    "LEE Yi-Chieh",
    "LEK Hsiang Hui",
    "Ben LEONG Wing Lup",
    "LEONG Hon Wai",
    "LEONG Tze Yun",
    "LEONG Wai Kay",
    "LEOW Wee Kheng",
    "Daren LER Shan Wen",
    "LI Jialin",
    "LI Xiaofan",
    "LIANG Zhenkai",
    "Brian LIM Youliang",
    "LIM Shi Ying",
    "LING Tok Wang",
    "LIU Lili",
    "LOH Yong Chye",
    "LOW Kian Hsiang",
    "LOW Kok Lim",
    "Richard MA Tianbai",
    "Vivek Sundar MAGESH",
    "Umang MATHUR",
    "Muhammad Rizki Aulia Rahman MAULANA",
    "Kuldeep S. MEEL",
    "Tulika MITRA",
    "Amirhassan MONAJEMI",
    "Niranjan NAGARAJAN",
    "Suranga Chandima NANAYAKKARA",
    "Akshay NARAYAN",
    "Prabhu NATARAJAN",
    "Ganesh NEELAKANTA IYER",
    "NG Hwee Tou",
    "NG See Kiong",
    "NG Teck Khim",
    "Victor NG Teck Wei",
    "OH Lih Bin",
    "OOI Beng Chin",
    "OOI Wei Tsang",
    "PEH Li Shiuan",
    "Jerry PING Wenjie",
    "Ivan PNG Paak Liang",
    "Danny POO Chiang Choon",
    "Adi Yoga Sidi PRABAWA",
    "QIAO Dandan",
    "Vaibhav RAJAN",
    "Damith Chatura RAJAPAKSE",
    "Anand Mohan RAMCHAND",
    "Kisenchand Nathumal RANAI",
    "Sanka RASNAYAKA",
    "Frank Patrick REBENTROST",
    "Manuel RIGGER",
    "Abhik ROYCHOUDHURY",
    "Prateek SAXENA",
    "Jonathan SCARLETT",
    "Ilya SERGEY",
    "Rudy SETIONO",
    "SHAO Lin",
    "Reza SHOKRI",
    "SHOU Zheng, Mike",
    "Terence SIM Mong Cheng",
    "Alex SIOW Yuen Khong",
    "Rajendra Prasad SIRIGINA",
    "Harold SOH Soon Hong",
    "SOO Yuen Jien",
    "SOW Jin Sze",
    "Frank Christian STEPHAN",
    "Sufatrio",
    "Vivy SUHENDRA",
    "Warut SUKSOMPONG",
    "SUN Chenshuo",
    "Ravi SUPPIAH",
    "Aaron TAN Tuck Choy",
    "Bernard TAN Cheng Yian",
    "TAN Chuan Hoo",
    "Colin TAN Keng Yan",
    "Gary TAN Soon Huat",
    "TAN Kian Lee",
    "Robby Tantowi TAN",
    "Sharon TAN Swee Lin",
    "TAN Sun Teck",
    "TAN Tiow Seng",
    "TAN Wee Kek",
    "Welly TANTONO",
    "TAY Yong Chiang",
    "TEO Hock Hai",
    "TEO Tat Khai",
    "TEO Yong Meng",
    "Anthony TUNG Kum Hoe",
    "Jithin VACHERY",
    "Prasanna Karthik VAIRAM",
    "Ambuj VARSHNEY",
    "Prashant Nalini VASUDEVAN",
    "Bimlesh WADHWA",
    "WANG Jingxian",
    "WANG Qiuhong",
    "WANG Ye",
    "Christian Von Der WETH",
    "WONG Lim Soon",
    "WONG Weng Fai",
    "XIAO Xiaokui",
    "Shamantha YAN Shiya",
    "Shane YAN Shiyan",
    "YANG Lu",
    "Angela YAO Yingjie",
    "Roland YAP Hock Chuan",
    "YEO Wee Kiang",
    "Francis YEOH",
    "YOU Yang",
    "YU Haifeng",
    "ZHAI Yingda",
    "ZHANG Jiaheng",
    "ZHANG Yang",
    "ZHAO Jin",
    "ZHAO Rui",
    "ZHAO Yiliang",
    "ZHOU Lifeng",
    "Roger ZIMMERMANN"
]

// for (let i = 0; i < names.length; i++) {
//     console.log(names[i])
//     const response = await axios.post("http://localhost:3500/professors", { 
//         "name" : names[i]
//     });
//     console.log(response.data.message)
// }

const reviews = [
    {
        "quality": 5,
        "difficulty": 5,
        "course": "CS2109S",
        "profName": "Ben LEONG Wing Lup",
        "date": "2020-08-01",
        "content": "Very good prof, but very difficult course"
    },
    {
        "quality": 3,
        "difficulty": 5,
        "course": "CS2109S",
        "profName": "Ben LEONG Wing Lup",
        "date": "2021-08-01",
        "content": "I found this course very difficult to understand, very theory heavy."
    },
    {
        "quality": 3,
        "difficulty": 4,
        "course": "BT1101",
        "profName": "Sharon TAN Swee Lin",
        "date": "2021-08-01",
        "content": "This course's pace was too fast, I found it hard to understand, but the content was useful for future courses."
    },
    {
        "quality": 2,
        "difficulty": 5,
        "course": "CS2103T",
        "profName": "Damith Chatura RAJAPAKSE",
        "date": "2022-08-01",
        "content": "This course had a very high workload, and I think that it did not really prepare me well for an internship."
    },
    {
        "quality": 5,
        "difficulty": 5,
        "course": "CS1231S",
        "profName": "Aaron Tan Tuck Choy",
        "date": "2020-08-01",
        "content": "This course had a very high workload, but I think it helped me build my foundation for future CS courses."
    },
    {
        "quality": 4,
        "difficulty": 3,
        "course": "CS2105",
        "profName": "Zhou Lifeng",
        "date": "2023-08-01",
        "content": "A relatively easy course, but I think more could be taught in the course."
    },
    {
        "quality": 3,
        "difficulty": 2,
        "course": "IS1108",
        "profName": "Boon Kee LEE",
        "date": "2023-08-01",
        "content": "A relatively easy course, but I did not find it very relavant."
    },
    {
        "quality": 5,
        "difficulty": 4,
        "course": "CS1010",
        "profName": "OOI Wei Tsang",
        "date": "2023-08-01",
        "content": "A pretty tough course to introduce us to basic programming, but I'm glad I survived it and became a better coder."
    },
]


for (let i = 0; i < reviews.length; i++) {
    console.log(reviews[i])
    const response = await axios.post("http://localhost:3500/reviews", reviews[i]);
    console.log(response.data.message)
}

